### ISSUE TITLE
4.23.4 is broken 

### ISSUE THREAD

**Issue by zhouxinghong** [SublimeLinter/SublimeLinter#1928]
4.23.4 is broken 
Windows 10 19044
ST4 4169

**Comment by zhouxinghong** [comment]
Officially, because 3.12 is not supported, all Sublime*** software packages that depend on SublimeLinter cannot run properly. Hope you can solve this problem soon, thank you very much! 🎉

**Comment by kaste** [comment]
Hm,  don't know what you mean here unfortunately.  SublimeLinter runs only on SublimeText's plugin host.  The (this) code actually runs on python 3.3 atm.  The actual linters run on your system, as native processes, using the systems python, a virtual environment etc.

**Comment by zhouxinghong** [comment]
My local development environment is installed with Python 3.12. When installing this extension, the console throws a lot of error messages.

**Comment by zhouxinghong** [comment]
If you don’t believe me, you can switch the environment to Python 3.12 and give it a try.

**Comment by silentbugs** [comment]
On MacOS Sonoma 14.4 with python 3.12.2 SublimeLinter fails with the following error:

```
reloading python 3.3 plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 14, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/log_handler.py", line 5, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
```

**Comment by zhouxinghong** [comment]
The same error also exists on Windows 10 systems, and due to this error, other sub-extensions that depend on this extension will not run. For example, SublimeLinter-pylint and other extensions. . .

**Comment by kaste** [comment]
@silentbugs I only know these kind of stacktraces when Package Control updates SublimeLinter and somehow it fails to reload the plugin.  Usually these kind of errors go away just by restarting Sublime Text.  Still watch the console closely after the restart because maybe Package Control updates other things and is not done yet. 

@zhouxinghong Do you have the same stack trace.  Then it is likely also a failure to update (hot-reload) SublimeLinter.  If you have a different trace just post it.   

Please note that the first line says `reloading python 3.3 plugin SublimeLinter.sublime_linter`.  We're running not your systems python, that's the old 3.3.  (Actually I pushed this recent update to SublimeLinter to prepare an upgrade to Python 3.8 but maybe I messed up the automatic upgrading.)  

BTW I'm on Windows 11 and my main python is 

```
> python -V
Python 3.12.2
```

**Comment by silentbugs** [comment]
@kaste Understood, thanks for the information. I noticed the bundled python a little too late!

I have restarted Sublime Text and I'm still getting this error. I've tried removing and re-installing SublimeLinter (I was also using SublimeLinter-flake8 but have removed it) and I'm getting the following:

```
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed package "SublimeLinter" 4.23.4
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin SublimeLinter.__init__
reloading python 3.3 plugin SublimeLinter._init
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/_init.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/vendor/jsonschema/__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/vendor/jsonschema/validators.py", line 170, in <module>
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/vendor/jsonschema/_utils.py", line 59, in load_schema
NotADirectoryError: [Errno 20] Not a directory: '/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/vendor/jsonschema/schemas/draft3.json'
reloading python 3.3 plugin SublimeLinter.active_linters_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/active_linters_view.py", line 8, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading python 3.3 plugin SublimeLinter.busy_indicator_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/busy_indicator_view.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading python 3.3 plugin SublimeLinter.goto_commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/goto_commands.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading python 3.3 plugin SublimeLinter.highlight_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/highlight_view.py", line 13, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading python 3.3 plugin SublimeLinter.log_handler
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/log_handler.py", line 5, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading python 3.3 plugin SublimeLinter.panel_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/panel_view.py", line 10, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading python 3.3 plugin SublimeLinter.quick_actions
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/quick_actions.py", line 4, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading python 3.3 plugin SublimeLinter.status_bar_view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/status_bar_view.py", line 4, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading python 3.3 plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 14, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/log_handler.py", line 5, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/__init__.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 17, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/persist.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/silentz0r/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/settings.py", line 4, in <module>
ImportError: cannot import name events
reloading settings Packages/User/Preferences.sublime-settings
generating syntax summary
Package Control: resuming indexer
reloading settings Packages/User/Preferences.sublime-settings
```

Also, if it's of interest, this is the python version checked in Sublime's console:

>>> import sys
>>> sys.version
'3.8.12 (default, Dec  7 2022, 15:00:02) \n[Clang 15.0.3 (https://github.com/tru/llvm-release-build c98e08626c3c6d4f184f49'

**Comment by n-poland** [comment]
I am also hitting this issue. I was able to get around it by:
```
cd /Users/{username}/Library/Application Support/Sublime Text/Packages
git clone https://github.com/SublimeLinter/SublimeLinter.git
```

Which is a bit strange. It seems like everything breaks down after the first exception:
```
NotADirectoryError: [Errno 20] Not a directory: '/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/vendor/jsonschema/schemas/draft3.json'
```

Not quite sure what/when/how this broke, but it did at some point. Now the one package manager installs and updates to seems problematic.

**Comment by kaste** [comment]
I have a hotfix #1929

**Comment by kaste** [comment]
I messed this one up.  As you can see, @n-poland noticed it, running the zipped (installed) plugin throws, and the unpacked one, like the git clone, works.  Guess what, I use the git clone variant as I'm the developer here  😬

**Comment by kaste** [comment]
4.23.5 is live on Package Control.  From my testing the automatic package reload after the update did not work.  Restarting Sublime worked for me.  Thanks for taking the time to open the issue.

**Comment by silentbugs** [comment]
After updating and restarting Sublime it seems to work fine.

Thanks for the quick fix!

**Comment by zhouxinghong** [comment]
I also need to thank you very much for fixing it quickly and efficiently, and again, thank you very much, and to all involved, have a nice life! 🎉🎉👏👍😜😜🎉🎉👏👍😜

**Comment by kaste** [comment]
Glad it works.

**Comment by zhouxinghong** [comment]
I will say this: I hadn't realized before that the Sublime platform is so great!   After 2 days of using Sublime, I think the design concept, product thinking and reliability of the Sublime platform is very suitable for my current usage scenario. So today, I've decided to abandon VScode, which I've been using for years and which is a bloated, bulky, and difficult beast to use. I'll be using Sublime instead of VSCode for all my development work.
  😜🤞 Also here's wishing the Sublime platform and all the people who contribute to the Sublime platform to live, work, and be better and more awesome! 🎉👏🤞😜🏆💗

**Comment by IPWright83** [comment]
@zhouxinghong you should check out @kaste's other plugins https://github.com/timbrel/GitSavvy is absolutely brilliant. Keyboard driven source control within Sublime ❤️

**Comment by zhouxinghong** [comment]
@IPWright83 Thank you very much, teacher, for your enthusiastic guidance! You are very cool 👍🎉😜😜😜
